version: '3'

volumes:
  db:
    driver: local
  frontend:
    driver: local

services:
  app:
    build: .
    command: [bash, -c, bundle exec rails db:create && bundle exec puma -C config/puma.rb]
    depends_on:
      - db
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./:/root
      - /root/node_modules
      - /root/vendor
      - /root/.bundle
      - /root/.git
    working_dir: /root

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql

  frontend:
    image: node:12-alpine
    command: [yarn, serve]
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: .env
    # TODO: Need to wait frontend_modules
    depends_on:
      - frontend_modules
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/root
      - frontend:/root/node_modules
    working_dir: /root

  frontend_modules:
    image: node:12-alpine
    command: [yarn, install]
    volumes:
      - ./frontend:/root
      - frontend:/root/node_modules
    working_dir: /root

  web:
    depends_on:
      - app
    image: nginx:1.17-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/srv
      - ./tmp:/root
