version: '3'

volumes:
  db:
    driver: local

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql
    env_file: .env
