version: '3'

volumes:
  db:
    driver: local

services:

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql

  web:
    image: nginx:1.17-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/srv
      - ./tmp:/root
    command: /bin/sh -c "envsubst '$$APP_HOST $$APP_PORT' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file: .env
