:dynamic: true
:dynamic_every: 5s
:enabled: true
:scheduler:
  :listened_queues_only: false
:schedule:
  user_import_worker:
    class: UserImportWorker
    cron: "0 * * * * *"

  auth0_job_status_update_worker:
    class: Auth0JobStatusUpdateWorker
    cron: "5 */2 * * * *"
